<a href="https://colab.research.google.com/github/sriraj934/-Heart-failure-Prediction/blob/main/Heart_failure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Heart Failure Clinic Record

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('heart_failure_clinical_records_dataset.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

In [3]:
print(X)

[[7.500e+01 0.000e+00 5.820e+02 ... 1.000e+00 0.000e+00 4.000e+00]
 [5.500e+01 0.000e+00 7.861e+03 ... 1.000e+00 0.000e+00 6.000e+00]
 [6.500e+01 0.000e+00 1.460e+02 ... 1.000e+00 1.000e+00 7.000e+00]
 ...
 [4.500e+01 0.000e+00 2.060e+03 ... 0.000e+00 0.000e+00 2.780e+02]
 [4.500e+01 0.000e+00 2.413e+03 ... 1.000e+00 1.000e+00 2.800e+02]
 [5.000e+01 0.000e+00 1.960e+02 ... 1.000e+00 1.000e+00 2.850e+02]]


In [4]:
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1
 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 0 1 1 1 1 1 0 0 1 0
 1 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1
 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0
 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1
 1 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0]


## Splitting the data into training and test set

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size = 0.2,random_state=0)

In [6]:
print(X_train)

[[8.10e+01 0.00e+00 4.54e+03 ... 1.00e+00 1.00e+00 1.07e+02]
 [5.00e+01 0.00e+00 1.85e+02 ... 1.00e+00 1.00e+00 1.12e+02]
 [4.50e+01 0.00e+00 5.82e+02 ... 1.00e+00 0.00e+00 6.10e+01]
 ...
 [8.50e+01 1.00e+00 1.02e+02 ... 0.00e+00 0.00e+00 9.40e+01]
 [6.00e+01 0.00e+00 5.82e+02 ... 1.00e+00 1.00e+00 4.00e+01]
 [7.00e+01 1.00e+00 1.71e+02 ... 1.00e+00 1.00e+00 1.46e+02]]


In [7]:
print(X_test)

[[4.0000000e+01 1.0000000e+00 1.0100000e+02 0.0000000e+00 4.0000000e+01
  0.0000000e+00 2.2600000e+05 8.0000000e-01 1.4100000e+02 0.0000000e+00
  0.0000000e+00 1.8700000e+02]
 [6.0667000e+01 1.0000000e+00 1.5100000e+02 1.0000000e+00 4.0000000e+01
  1.0000000e+00 2.0100000e+05 1.0000000e+00 1.3600000e+02 0.0000000e+00
  0.0000000e+00 1.7200000e+02]
 [4.5000000e+01 1.0000000e+00 9.8100000e+02 0.0000000e+00 3.0000000e+01
  0.0000000e+00 1.3600000e+05 1.1000000e+00 1.3700000e+02 1.0000000e+00
  0.0000000e+00 1.1000000e+01]
 [5.5000000e+01 0.0000000e+00 5.8200000e+02 1.0000000e+00 3.5000000e+01
  1.0000000e+00 3.7100000e+05 7.0000000e-01 1.4000000e+02 0.0000000e+00
  0.0000000e+00 1.9700000e+02]
 [7.0000000e+01 0.0000000e+00 2.3200000e+02 0.0000000e+00 3.0000000e+01
  0.0000000e+00 1.7300000e+05 1.2000000e+00 1.3200000e+02 1.0000000e+00
  0.0000000e+00 2.1000000e+02]
 [6.5000000e+01 1.0000000e+00 5.9000000e+01 1.0000000e+00 6.0000000e+01
  0.0000000e+00 1.7200000e+05 9.0000000e-01 1.3700000

In [8]:
print(y_train)

[0 0 1 0 0 0 0 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 1 1 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 1 1 0 1 0 1 0 0 0 0 1 0 0 1 1
 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 0 1 1 0 0 1 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0 0 1 1 1 0 0 0 0
 0 1 0 0 0 0 0 0 1 0 0 1 1 0 1 0 0 1 0 0 0 0 0 1 0 1 1 0 1 0 0 0 1 1 0 0 1
 1 1 0 0 1 1 0 0 0 1 1 0 0 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0
 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0]


In [9]:
print(y_test)

[0 0 1 0 0 0 0 0 1 0 0 1 1 1 1 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 1 0 1 1 0
 1 0 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 1 1 0 1 0 0]


## Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
print(X_train)

[[ 1.70455927 -0.89274435  4.04602991 ...  0.73616267  1.46449201
  -0.29449203]
 [-0.92576852 -0.89274435 -0.39339316 ...  0.73616267  1.46449201
  -0.2297298 ]
 [-1.35001494 -0.89274435  0.01130281 ...  0.73616267 -0.68283063
  -0.89030457]
 ...
 [ 2.0439564   1.1201415  -0.47800215 ... -1.35839541 -0.68283063
  -0.46287383]
 [-0.07727569 -0.89274435  0.01130281 ...  0.73616267  1.46449201
  -1.16230595]
 [ 0.77121715  1.1201415  -0.40766456 ...  0.73616267  1.46449201
   0.21065339]]


## Training the data

In [12]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Predicting the Test set

In [13]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]]


## Making Confusion Matrix

In [14]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[36  1]
 [12 11]]


0.7833333333333333

## K-fold Cross Validation

In [15]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier , X =X_train , y=y_train, cv = 10)
print("Accuracy : {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation : {:.2f} %".format(accuracies.std()*100))

Accuracy : 84.53 %
Standard Deviation : 4.15 %
